[package]
name = "a14"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opener = "0.5"
rand = { version = "0.8.3", features = ["small_rng"] }
